name: GCG Hakush Compare

on:
  workflow_dispatch:
    inputs:
      old:
        description: 'Old Version (like 4.5 | 4.5.54)'
        required: true
      new:
        description: 'New Version (latest when default)'
        required: false

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        pip install requests
        pip install tqdm

    - name: Running With Default New
      if: ${{ github.event.inputs.new == '' || github.event.inputs.new == 'latest' }}
      run: python main.py --old "${{ github.event.inputs.old }}"  --save true

    - name: Running With Default New
      if: ${{ github.event.inputs.new != '' && github.event.inputs.new != 'latest' }}
      run: python main.py --old "${{ github.event.inputs.old }}"  --new "${{ github.event.inputs.new }}" --save true

    - name: file1
      uses: actions/upload-artifact@v2
      with:
        name: actions_compare.json
        path: actions_compare.json
          
    - name: file2
      uses: actions/upload-artifact@v2
      with:
        name: characters_compare.json
        path: characters_compare.json
          
    - name: file3
      uses: actions/upload-artifact@v2
      with:
        name: actions_compare.md
        path: actions_compare.md
